name: Validate HEF JSON

on:
  push:
    paths:
      - 'example.hef.json'
      - 'schemas/**'
      - 'validate.py'
      - '.github/workflows/validate.yml'
  pull_request:
    paths:
      - 'example.hef.json'
      - 'schemas/**'
      - 'validate.py'
      - '.github/workflows/validate.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install jsonschema
      - name: Run validation
        run: python validate.py
